### ISSUE TITLE
Compiler error misising test cases and off by one

### ISSUE THREAD

**Issue by karlek** [EmilGedda/hattis#3]
When having a compile error the total number of test cases are missing and the test case is off by one (`1 of 0`)

![out346](https://cloud.githubusercontent.com/assets/1278705/20054132/ced02afa-a4db-11e6-9639-7f9b90be7bcb.png)

**Comment by EmilGedda** [comment]
Good catch, will probably fix this by simply remove "on test case [...]" whenever a Compile Error occurs since it is not really a necessary thing to display
