### ISSUE TITLE
Better description for timeouts

### ISSUE THREAD

**Issue by karlek** [EmilGedda/hattis#5]
If you are making quick edits and uploading to kattis, it can happen that you are timed out for certain time (usually 1 or 2 minutes). 

Hattis receives a 404 error and the submission id becomes the seconds counter until one can submit again.

I propose a better description where it explicitly tells you that you've been timed out and that you can submit again in `$duration_left` seconds.

![out24261](https://cloud.githubusercontent.com/assets/1278705/20054461/6299f4f4-a4dd-11e6-9540-b28795d81927.png)

**Comment by EmilGedda** [comment]
Yep, this was on my mind aswell and should be fairly easy to implement, it all depends on how the non-documented API kattis provides for scripts, but seeing as how Submission ID already parsed the correct counter I dont think there will be any problem implementing this, I'll get right on it.

This will be added to 1.1 along with Makefile-generation and all the other bugfixes, with a release hopefully before the weekend.

**Comment by karlek** [comment]
I hijack this issue to discuss a future feature: auto-submit after timeout. `hattis` could sleep for the timeout duration while counting down and then automatically submit your file after the timeout has been lifted.

**Comment by EmilGedda** [comment]
Hmm, yes this seems like a feature that would be pretty handy, overloading `--force` to wait for new tokens and then resubmitting. The code base related to console output needs some refactoring aswell so that might be a thing to add in the future.
